baseURL: "https://team4autism.github.io"
languageCode: "en-gb"
title: "Learn Autism"
theme: "PaperMod"

params:

    author: "May Dziedziak"
    disableThemeToggle: false
    hideFooter: true
    hideMeta: true

    homeInfoParams:
        Title: Learn Autism
        Content: |
          **Autism spectrum disorder** (ASD) is a neurological and developmental disorder 
          that affects how people interact with others, communicate, learn, and behave. Autism is a spectrum condition
          and affects people in different ways.

    socialIcons:
        - name: "Instagram"
          url: "<link>"
        - name: "TikTok"
          url: "https://www.tiktok.com/@learn.autism"
        - name: "email"
          url: "mailto:team4autism@gmail.com"

    assets:
        favicon16x16: "favicon16.png"            # Logo 16x16 pixels
        favicon32x32: "favicon32.png"            # Logo 32x32 pixels
        apple_touch_icon: "apple-touch-icon.png" # Logo 180x180 i guess

    label:
        text: "Home"
        # icon: "/apple-touch-icon.png" # Logo highest resolution possible
